### PR TITLE
Add /download command

### PR DESCRIPTION
**Pull request by denverquane**
Adds functionality that allows guild admins to download relevant data for their guild.

These correspond to the Postgres tables:
`guilds` (downloads the ID and name of the current guild)
`users` (downloads the user entries of users that have played on the guild, and are opted in to data collection)
`users_games` (detailed user game history, same filtering criteria as `users` above)
`games` (games played on the guild)
`game_events` (all game events for games played on the guild)

### CODE REVIEW

**Comment by kurokobo** [comment]
https://github.com/automuteus/utils/pull/8

**Comment by kurokobo** [comment]
https://github.com/automuteus/deploy/pull/14

**Comment by kurokobo** [comment]
I don't know if any guilds will face this problem, but it appears that the file size that bot can attach is limited to 8 MB.
I tried generating dummy data over 8 MB and invoking `/download`, then the interaction failed.

image

**Comment by denverquane** [comment]
Yeah I had this thought as well. I'll probably throw in a simple check, but I (hope) it would be hard to have 8MB of data in a single table for a single guild. Haven't done the math on how much rows or games that would end up being, though. But you're right, giving some feedback why it failed would be a good idea overall

**Comment by kurokobo** [comment]
> it would be hard to have 8MB of data in a single table for a single guild

Agree with you 😃 I think it would be okay to implement it after someone faced it and reported the issue.

**Pull request merged**
